alias air="cd ~/dev/airbnb"
alias dev="cd ~/dev"
alias rebash="source ~/.bash_profile"
alias start_redis="/usr/local/bin/redis-server"
alias start_lucene="~/dev/backend/services/search/bin/start-search-dev.bash"
alias emr="elastic-mapreduce"
